plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
    // id("com.google.gms.google-services") // enable with google-services.json
}

/**
 * Signaling endpoint, overridable per build without editing this file:
 *
 *   ./gradlew assembleDebug -PsignalingUrl=wss://signal.example.com
 *
 * The debug default is the Android emulator's alias for host loopback. It is
 * NOT reachable from a physical handset, so any real-device test (A03 or Vivo)
 * must pass -PsignalingUrl pointing at a server both phones can reach over the
 * internet. Leaving it hardcoded is why a debug APK sideloaded onto the A03
 * could never connect.
 */
val signalingUrlOverride: String? = project.findProperty("signalingUrl") as String?
val debugSignalingUrl = signalingUrlOverride ?: "ws://10.0.2.2:8080"
val releaseSignalingUrl = signalingUrlOverride ?: "wss://signal.yourdomain.com"

/**
 * Cleartext is denied by default from API 28 on, so a debug build pointed at a
 * plain `ws://` broker fails to connect at all — silently, because OkHttp's
 * failure surfaces as a reconnect rather than an error the tester can see.
 *
 * The generated config below re-permits cleartext for exactly one host: the one
 * `-PsignalingUrl` names, and only when that URL is `ws://`. It is applied from
 * `src/debug/AndroidManifest.xml`, so a release build keeps the platform default
 * and no shipped artifact ever carries a cleartext exemption.
 */
val debugCleartextHost: String? =
    Regex("^ws://([^:/?#]+)").find(debugSignalingUrl)?.groupValues?.get(1)

abstract class GenerateNetworkSecurityConfig : DefaultTask() {
    /** Host allowed to speak cleartext. Absent means: allow nothing. */
    @get:Input @get:Optional abstract val cleartextHost: Property<String>

    @get:OutputDirectory abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val host = cleartextHost.orNull
        val exemption = if (host == null) "" else """
            |    <domain-config cleartextTrafficPermitted="true">
            |        <domain includeSubdomains="false">$host</domain>
            |    </domain-config>
        """.trimMargin()
        val xmlDir = outputDirectory.get().asFile.resolve("xml").apply { mkdirs() }
        xmlDir.resolve("network_security_config.xml").writeText(
            """
            |<?xml version="1.0" encoding="utf-8"?>
            |<!-- GENERATED by :app:generateDebugNetworkSecurityConfig — do not edit. -->
            |<network-security-config>
            |    <base-config cleartextTrafficPermitted="false"/>
            |$exemption
            |</network-security-config>
            |
            """.trimMargin()
        )
    }
}

androidComponents {
    onVariants { variant ->
        if (variant.buildType != "debug") return@onVariants
        val task = tasks.register<GenerateNetworkSecurityConfig>(
            "generate${variant.name.replaceFirstChar { it.uppercase() }}NetworkSecurityConfig"
        ) {
            debugCleartextHost?.let { cleartextHost.set(it) }
        }
        variant.sources.res?.addGeneratedSourceDirectory(
            task, GenerateNetworkSecurityConfig::outputDirectory
        )
    }
}

android {
    namespace = "com.remoteassist"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.remoteassist"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"

        // Point the app at your signaling server. Override per build type as needed.
        buildConfigField("String", "SIGNALING_URL", "\"$debugSignalingUrl\"")
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }

    // The telephony/audio unit tests exercise pure logic, but some of it sits in
    // files that also reference android.* constants. Returning defaults keeps
    // those from throwing "not mocked" instead of running the assertion.
    testOptions {
        unitTests.isReturnDefaultValues = true
    }

    // The cross-language protocol fixtures live at the repository root, outside
    // the Gradle build, because Node and (from W2) .NET read the very same
    // files. Mounting them as unit-test resources is what lets the Kotlin
    // implementation be held to the identical vectors rather than to a copy that
    // can quietly drift. See protocol/README.md.
    sourceSets {
        getByName("test") {
            resources.srcDir(rootProject.file("../protocol/fixtures"))
        }
    }

    buildTypes {
        debug {
            // 10.0.2.2 = host loopback from the Android emulator (default only)
            buildConfigField("String", "SIGNALING_URL", "\"$debugSignalingUrl\"")
        }
        release {
            isMinifyEnabled = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            buildConfigField("String", "SIGNALING_URL", "\"$releaseSignalingUrl\"")
        }
    }
}

dependencies {
    // WebRTC (community prebuilt)
    implementation("io.github.webrtc-sdk:android:125.6422.07")

    // Signaling transport
    implementation("com.squareup.okhttp3:okhttp:4.12.0")

    // Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")

    // Compose
    implementation(platform("androidx.compose:compose-bom:2024.09.03"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.activity:activity-compose:1.9.2")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.6")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.6")
    debugImplementation("androidx.compose.ui:ui-tooling")

    // Core + security-crypto (EncryptedSharedPreferences)
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.security:security-crypto:1.1.0-alpha06")
    implementation("androidx.biometric:biometric:1.2.0-alpha05")

    // FCM (wake device). Requires google-services plugin + google-services.json.
    implementation(platform("com.google.firebase:firebase-bom:33.4.0"))
    implementation("com.google.firebase:firebase-messaging-ktx")

    // QR generation (session code) + scanning (CameraX + ML Kit barcode)
    implementation("com.google.zxing:core:3.5.3")
    implementation("androidx.camera:camera-core:1.3.4")
    implementation("androidx.camera:camera-camera2:1.3.4")
    implementation("androidx.camera:camera-lifecycle:1.3.4")
    implementation("androidx.camera:camera-view:1.3.4")
    implementation("com.google.mlkit:barcode-scanning:17.3.0")

    // Unit tests
    testImplementation("junit:junit:4.13.2")
    // Real org.json on the unit-test classpath. The android.jar stub returns
    // default values (see testOptions.unitTests.isReturnDefaultValues), which
    // would make every JSON assertion vacuously pass instead of exercising the
    // control-frame parser. Test-only: it is not packaged into the APK.
    testImplementation("org.json:json:20240303")
}
